server:
  port: ${port:8082}

spring:
  profiles:
    active: cloud
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: '*'

config:
  key: jose
